/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesRouteImport } from './routes/$series'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArIndexRouteImport } from './routes/ar/index'
import { Route as ArSeriesRouteImport } from './routes/ar/$series'
import { Route as ArAboutRouteImport } from './routes/ar/about'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as EssaysIndexRouteImport } from './routes/essays/index'
import { Route as EssaysIdRouteImport } from './routes/essays/$id'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as LogsIdRouteImport } from './routes/logs/$id'
import { Route as ThreadsThreadRouteImport } from './routes/threads/$thread'
import { Route as ArBooksIndexRouteImport } from './routes/ar/books/index'
import { Route as ArEssaysIndexRouteImport } from './routes/ar/essays/index'
import { Route as ArEssaysIdRouteImport } from './routes/ar/essays/$id'
import { Route as ArLogsIndexRouteImport } from './routes/ar/logs/index'
import { Route as ArLogsIdRouteImport } from './routes/ar/logs/$id'
import { Route as ArThreadsThreadRouteImport } from './routes/ar/threads/$thread'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/$series',
  path: '/$series',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/ar/',
  path: '/ar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArSeriesRoute = ArSeriesRouteImport.update({
  id: '/ar/$series',
  path: '/ar/$series',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAboutRoute = ArAboutRouteImport.update({
  id: '/ar/about',
  path: '/ar/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysIndexRoute = EssaysIndexRouteImport.update({
  id: '/essays/',
  path: '/essays/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysIdRoute = EssaysIdRouteImport.update({
  id: '/essays/$id',
  path: '/essays/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIdRoute = LogsIdRouteImport.update({
  id: '/logs/$id',
  path: '/logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadRoute = ThreadsThreadRouteImport.update({
  id: '/threads/$thread',
  path: '/threads/$thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ArBooksIndexRoute = ArBooksIndexRouteImport.update({
  id: '/ar/books/',
  path: '/ar/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArEssaysIndexRoute = ArEssaysIndexRouteImport.update({
  id: '/ar/essays/',
  path: '/ar/essays/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArEssaysIdRoute = ArEssaysIdRouteImport.update({
  id: '/ar/essays/$id',
  path: '/ar/essays/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArLogsIndexRoute = ArLogsIndexRouteImport.update({
  id: '/ar/logs/',
  path: '/ar/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArLogsIdRoute = ArLogsIdRouteImport.update({
  id: '/ar/logs/$id',
  path: '/ar/logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArThreadsThreadRoute = ArThreadsThreadRouteImport.update({
  id: '/ar/threads/$thread',
  path: '/ar/threads/$thread',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$series': typeof SeriesRoute
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/$series': typeof ArSeriesRoute
  '/ar/about': typeof ArAboutRoute
  '/essays/$id': typeof EssaysIdRoute
  '/logs/$id': typeof LogsIdRoute
  '/threads/$thread': typeof ThreadsThreadRoute
  '/ar/': typeof ArIndexRoute
  '/books/': typeof BooksIndexRoute
  '/essays/': typeof EssaysIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/ar/essays/$id': typeof ArEssaysIdRoute
  '/ar/logs/$id': typeof ArLogsIdRoute
  '/ar/threads/$thread': typeof ArThreadsThreadRoute
  '/ar/books/': typeof ArBooksIndexRoute
  '/ar/essays/': typeof ArEssaysIndexRoute
  '/ar/logs/': typeof ArLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$series': typeof SeriesRoute
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/$series': typeof ArSeriesRoute
  '/ar/about': typeof ArAboutRoute
  '/essays/$id': typeof EssaysIdRoute
  '/logs/$id': typeof LogsIdRoute
  '/threads/$thread': typeof ThreadsThreadRoute
  '/ar': typeof ArIndexRoute
  '/books': typeof BooksIndexRoute
  '/essays': typeof EssaysIndexRoute
  '/logs': typeof LogsIndexRoute
  '/ar/essays/$id': typeof ArEssaysIdRoute
  '/ar/logs/$id': typeof ArLogsIdRoute
  '/ar/threads/$thread': typeof ArThreadsThreadRoute
  '/ar/books': typeof ArBooksIndexRoute
  '/ar/essays': typeof ArEssaysIndexRoute
  '/ar/logs': typeof ArLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$series': typeof SeriesRoute
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/$series': typeof ArSeriesRoute
  '/ar/about': typeof ArAboutRoute
  '/essays/$id': typeof EssaysIdRoute
  '/logs/$id': typeof LogsIdRoute
  '/threads/$thread': typeof ThreadsThreadRoute
  '/ar/': typeof ArIndexRoute
  '/books/': typeof BooksIndexRoute
  '/essays/': typeof EssaysIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/ar/essays/$id': typeof ArEssaysIdRoute
  '/ar/logs/$id': typeof ArLogsIdRoute
  '/ar/threads/$thread': typeof ArThreadsThreadRoute
  '/ar/books/': typeof ArBooksIndexRoute
  '/ar/essays/': typeof ArEssaysIndexRoute
  '/ar/logs/': typeof ArLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$series'
    | '/about'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/ar/$series'
    | '/ar/about'
    | '/essays/$id'
    | '/logs/$id'
    | '/threads/$thread'
    | '/ar/'
    | '/books/'
    | '/essays/'
    | '/logs/'
    | '/ar/essays/$id'
    | '/ar/logs/$id'
    | '/ar/threads/$thread'
    | '/ar/books/'
    | '/ar/essays/'
    | '/ar/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$series'
    | '/about'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/ar/$series'
    | '/ar/about'
    | '/essays/$id'
    | '/logs/$id'
    | '/threads/$thread'
    | '/ar'
    | '/books'
    | '/essays'
    | '/logs'
    | '/ar/essays/$id'
    | '/ar/logs/$id'
    | '/ar/threads/$thread'
    | '/ar/books'
    | '/ar/essays'
    | '/ar/logs'
  id:
    | '__root__'
    | '/'
    | '/$series'
    | '/about'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/ar/$series'
    | '/ar/about'
    | '/essays/$id'
    | '/logs/$id'
    | '/threads/$thread'
    | '/ar/'
    | '/books/'
    | '/essays/'
    | '/logs/'
    | '/ar/essays/$id'
    | '/ar/logs/$id'
    | '/ar/threads/$thread'
    | '/ar/books/'
    | '/ar/essays/'
    | '/ar/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeriesRoute: typeof SeriesRoute
  AboutRoute: typeof AboutRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArSeriesRoute: typeof ArSeriesRoute
  ArAboutRoute: typeof ArAboutRoute
  EssaysIdRoute: typeof EssaysIdRoute
  LogsIdRoute: typeof LogsIdRoute
  ThreadsThreadRoute: typeof ThreadsThreadRoute
  ArIndexRoute: typeof ArIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  EssaysIndexRoute: typeof EssaysIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  ArEssaysIdRoute: typeof ArEssaysIdRoute
  ArLogsIdRoute: typeof ArLogsIdRoute
  ArThreadsThreadRoute: typeof ArThreadsThreadRoute
  ArBooksIndexRoute: typeof ArBooksIndexRoute
  ArEssaysIndexRoute: typeof ArEssaysIndexRoute
  ArLogsIndexRoute: typeof ArLogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$series': {
      id: '/$series'
      path: '/$series'
      fullPath: '/$series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/ar'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/$series': {
      id: '/ar/$series'
      path: '/ar/$series'
      fullPath: '/ar/$series'
      preLoaderRoute: typeof ArSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/about': {
      id: '/ar/about'
      path: '/ar/about'
      fullPath: '/ar/about'
      preLoaderRoute: typeof ArAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/': {
      id: '/essays/'
      path: '/essays'
      fullPath: '/essays/'
      preLoaderRoute: typeof EssaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/$id': {
      id: '/essays/$id'
      path: '/essays/$id'
      fullPath: '/essays/$id'
      preLoaderRoute: typeof EssaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$id': {
      id: '/logs/$id'
      path: '/logs/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof LogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$thread': {
      id: '/threads/$thread'
      path: '/threads/$thread'
      fullPath: '/threads/$thread'
      preLoaderRoute: typeof ThreadsThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/books/': {
      id: '/ar/books/'
      path: '/ar/books'
      fullPath: '/ar/books/'
      preLoaderRoute: typeof ArBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/essays/': {
      id: '/ar/essays/'
      path: '/ar/essays'
      fullPath: '/ar/essays/'
      preLoaderRoute: typeof ArEssaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/essays/$id': {
      id: '/ar/essays/$id'
      path: '/ar/essays/$id'
      fullPath: '/ar/essays/$id'
      preLoaderRoute: typeof ArEssaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/logs/': {
      id: '/ar/logs/'
      path: '/ar/logs'
      fullPath: '/ar/logs/'
      preLoaderRoute: typeof ArLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/logs/$id': {
      id: '/ar/logs/$id'
      path: '/ar/logs/$id'
      fullPath: '/ar/logs/$id'
      preLoaderRoute: typeof ArLogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/threads/$thread': {
      id: '/ar/threads/$thread'
      path: '/ar/threads/$thread'
      fullPath: '/ar/threads/$thread'
      preLoaderRoute: typeof ArThreadsThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeriesRoute: SeriesRoute,
  AboutRoute: AboutRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArSeriesRoute: ArSeriesRoute,
  ArAboutRoute: ArAboutRoute,
  EssaysIdRoute: EssaysIdRoute,
  LogsIdRoute: LogsIdRoute,
  ThreadsThreadRoute: ThreadsThreadRoute,
  ArIndexRoute: ArIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  EssaysIndexRoute: EssaysIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  ArEssaysIdRoute: ArEssaysIdRoute,
  ArLogsIdRoute: ArLogsIdRoute,
  ArThreadsThreadRoute: ArThreadsThreadRoute,
  ArBooksIndexRoute: ArBooksIndexRoute,
  ArEssaysIndexRoute: ArEssaysIndexRoute,
  ArLogsIndexRoute: ArLogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
